apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: steamuserapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: steamuserapi-api:latest
        imagePullPolicy: IfNotPresent
        command: ["python"]
        args: ["app.py"]
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: steamuserapi
spec:
  selector:
    app: api
  ports:
    - port: 5000
      targetPort: 5000
