apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: steamuserapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: steamuserapi-frontend:latest
        imagePullPolicy: IfNotPresent
        command: ["nginx"]
        args: ["-c", "/opt/nginx/conf/nginx.conf", "-g", "daemon off;"]
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: steamuserapi
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
